version: '3.2'
services:
  apache:
    container_name: nhs_apache
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./docker/apache/logs:/var/log/
      - ./html:/var/www/html
  perl:
    container_name: nhs_perl
    build:
      context: ./
      dockerfile: ./docker/perl/Dockerfile
    env_file:
      - ./docker/environment/users.env
    volumes:
      - ./html:/var/www/html
  database:
    container_name: nhs_postgres
    logging: 
      driver:
        none
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    command: ['postgres', '-c', 'log_statement=none', '-c', 'checkpoint_completion_target=0.9']
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ./docker/environment/users.env
    ports:
      - 5432:5432
