version: '3.2'
services:
  perl:
    container_name: nhs_perl
    build:
      context: ./
      dockerfile: ./docker/perl/Dockerfile
    command: ['hypnotoad', '-f', 'server.pl']
    env_file:
      - ./docker/environment/database.env
    ports:
      - '8082:8082'
  database:
    container_name: nhs_postgres
    logging: 
      driver:
        none
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    command: ['postgres', '-c', 'log_statement=none', '-c', 'checkpoint_completion_target=0.9']
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ./docker/environment/database.env
    ports:
      - 5432:5432
